name: Process and Upload Files on Push to Main

on:
  push:
    branches:
      - main

jobs:
  process-and-upload-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install axios

      - name: Process Files and Upload
        run: node ./scripts/processAndUploadFiles.js
        env:
          AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}
          NODE_TLS_REJECT_UNAUTHORIZED: '0'

