name: Process and Upload Files on Push to Main

on:
  push:
    branches:
      - main

jobs:
  process-and-upload-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11' 

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv 

      - name: Process Files and Upload
        run: python3 ./scripts/processAndUploadFiles.py
        env:
          AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}

